services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DB_SERVER: "dpg-crf75e3qf0us738grk0g-a"
      DB_NAME: "comex"
      DB_USER: "comex_user"
      DB_PASSWORD: "wyErecqW5DduLuwQ6AzNCBXnkE771Gdg"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: comex
      POSTGRES_USER: comex_user
      POSTGRES_PASSWORD: wyErecqW5DduLuwQ6AzNCBXnkE771Gdg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
