name: Deploy API

on:
  push:
    branches:
      - main  # ou o nome da branch que você deseja monitorar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Restore dependencies
        run: dotnet restore ComexAPI.csproj

      - name: Build
        run: dotnet build ComexAPI.csproj --configuration Release

      - name: Test
        run: dotnet test ComexAPI.csproj --configuration Release

      - name: Publish
        run: dotnet publish ComexAPI.csproj --configuration Release --output ./publish

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/YOUR_SERVICE_ID/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{}'

      - name: Run Migrations
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Running migrations..."
          export CONNECTION_STRING="Host=$DB_SERVER;Database=$DB_NAME;Username=$DB_USER;Password=$DB_PASSWORD;"
          dotnet tool restore
          dotnet ef database update --project ComexAPI.csproj --context ProdutoContext
