name: Deploy API

on:
  push:
    branches:
      - main # ou o nome da branch que você deseja monitorar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Restore dependencies
        run: dotnet restore ComexAPI.csproj

      - name: Build
        run: dotnet build ComexAPI.csproj --configuration Release

      - name: Test
        run: dotnet test ComexAPI.csproj --configuration Release

      - name: Publish
        run: dotnet publish ComexAPI.csproj --configuration Release --output ./publish

      - name: Run Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "Running migrations..."
          dotnet tool restore
          dotnet ef database update --project ComexAPI.csproj --context ProdutoContext --connection "$DATABASE_URL"
